name: Build and Test - Using FetchContent
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        build_type: ['Release']
        dep_version:
          - grpc: v1.47.1

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Dependencies (Linux)
        run: |
            sudo apt-get update
            sudo apt-get install -y \
              ccache \
              build-essential \
              autoconf libtool pkg-config libssl-dev

      - name: Cache Build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ matrix.build_type }}-${{ matrix.dep_version.grpc }}-cache
          restore-keys: |
            ${{ runner.os }}-${{ matrix.build_type }}-${{ matrix.dep_version.grpc }}-

      - name: Prepare ccache
        run: |
          ccache --max-size=1.0G
          ccache -V && ccache --show-stats && ccache --zero-stats

      - name: "Configure"
        run: |
          cmake -B build \
           -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
           -DGRPC_FETCHCONTENT=TRUE \
           -DGRPC_VERSION_TAG=${{ matrix.dep_version.grpc}} \
           -DgRPC_BUILD_TESTS=OFF

      - name: "Build"
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Show ccache stats
        run: |
          ccache -V && ccache --show-stats && ccache --zero-stats